language: php

php:
  - 5.6

cache:
  directories:
    - vendor
    - ~/.composer/cache

before_install: composer install --prefer-source --no-interaction

script: vendor/bin/phpunit

notifications:
  email: false