language: php

php:
  - 5.6
  - 7.1

script:
- $TRAVIS_BUILD_DIR/vendor/bin/phpunit
- $TRAVIS_BUILD_DIR/vendor/bin/phpdoc --sourcecode

install:
- composer install --no-interaction --prefer-source

after_success:
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  local-dir: target/api
  on:
    php: '7.1'
    branch: master

git:
  depth: 1